random_seed: False # options: False | <int>
# dataloading
# for simplicity clache is pre-applied
dataset_path: 'C:/Users/User/PycharmProjects/retinal-stuff/training-data/preprocess-output/histogram-hsv-s-clache-lab-no-inpaint'
mask_folder_path: 'c:/Users/User/PycharmProjects/retinal-stuff/training-data/retina-stuff-definitor/training-masks'

# eval_dataset_path: 'C:/Users/User/PycharmProjects/retinal-stuff/training-data/preprocess-output/histogram-hsv-s-clache-lab-no-inpaint'
# eval_mask_folder_path: 'c:/Users/User/PycharmProjects/retinal-stuff/training-data/retina-stuff-definitor/training-masks'

scan_subdirs: false  # Are the images organized in subfolders?
random_crop: False  # Set to false when dataset is 'celebahq', meaning only resize the images to img_shapes, instead of crop img_shapes from a larger raw image. This is useful when you train on images with different resolutions like places2. In these cases, please set random_crop to true.
batch_size: 4
k_folds: 10
num_workers: 0
num_epoch: 1500 # of training set reruns


#image sizing
img_shapes: [576, 576, 3]

# training
# resume training
# Empty to start new training
# model_restore: 'c:/Users/User/PycharmProjects/retinal-stuff/training-data/retina-stuff-definitor/for-display/checkpoints/states.pth'
model_restore: ''

# training
log_dir: 'C:/Users/User/PycharmProjects/retinal-stuff/training-data/retina-stuff-definitor/for-display/logs' # logging folder
checkpoint_dir: 'C:/Users/User/PycharmProjects/retinal-stuff/training-data/retina-stuff-definitor/for-display/checkpoints' # Checkpoint folder

use_cuda_if_available: True

opt_lr: 0.0001    # lr for Adam optimizer (generator)
opt_beta1: 0.9    # beta1 for Adam optimizer (generator)
opt_beta2: 0.999  # beta2 for Adam optimizer (generator)
weight_decay: 0 # 0.0000000001 # regularization weight


# max_iters: 500

# if optional: set to False to deactivate
display_iter: 6           # display dummy processing results
log_loss: True           # write losses to console and log
log_debug: False          # write debug info about changes and gradients to console
print_iter: 1           # display largest weight images
save_checkpoint_iter: 1   # save checkpoint file and overwrite last one
save_imgs_to_disc_iter: 1 # (optional) save image grids in checkpoint folder
save_cp_backup_iter: 10   # (optional) save checkpoint file named states_{n_iter}.pth

# loss
gan_loss: 'wbce' # options: 'wbce', 'bce', 'avg', 'wbceiou'
